import {Anek_Latin} from "next/font/google";
import "./globals.css";

const anekLatin = Anek_Latin({
  weight: ['400', '800'], // You can set the font weights you need
  subsets: ['latin'], // Select the character subsets you need
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${anekLatin.className}`}
      >
        {children}
      </body>
    </html>
  );
}
